-- ---------------------------------------------------------------------------
-- Corporate actions: from three types to ten.
--
-- Run this against an existing Supabase project before deploying the web build.
-- A fresh project set up from supabase/schema.sql already has this shape and
-- does not need it. Safe to run twice.
--
-- The desktop app manages its own SQLite schema and is unaffected by any of
-- this — see app/lib/store/sqlite.ts, which performs the equivalent migration
-- on first open.
--
-- What changes, and why:
--
--   * `action_type` was constrained to SPLIT / BONUS / MERGER / OTHER. Table 4
--     of the spec names ten types. The constraint is dropped rather than
--     widened: the list is expected to grow, and app/lib/corporate-actions.ts
--     is the authority on what is valid.
--
--   * `source` was constrained to 'manual' or 'auto'. Rows accepted from an
--     exchange lookup record where they came from — 'nse', 'nse+filing' — and
--     every one of those would have been rejected.
--
--   * `quantity_multiplier` was NOT NULL. A demerger or a buyback has no
--     multiplier; the ratio it is derived from now lives in its own columns.
--
--   * The unique key gains `target_key`. A demerger into four companies is four
--     rows on the same security and date, differing only in where the cost
--     goes. `target_key` is '' rather than NULL for the types that have no
--     target, because Postgres treats NULLs as distinct in a unique index and
--     one would stop it deduplicating anything.
-- ---------------------------------------------------------------------------

begin;

-- Drop the two check constraints by inspection rather than by name: the names
-- are generated by Postgres and differ between projects created at different
-- times.
do $$
declare
  c record;
begin
  for c in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where rel.relname = 'corporate_actions'
       and nsp.nspname = current_schema()
       and con.contype = 'c'
       and (pg_get_constraintdef(con.oid) ilike '%action_type%'
            or pg_get_constraintdef(con.oid) ilike '%source%')
  loop
    execute format('alter table corporate_actions drop constraint %I', c.conname);
  end loop;
end $$;

alter table corporate_actions
  alter column quantity_multiplier drop not null;

alter table corporate_actions
  add column if not exists ratio_from           numeric(18,6),
  add column if not exists ratio_to             numeric(18,6),
  add column if not exists target_isin          text,
  add column if not exists target_symbol        text,
  add column if not exists target_security_name text,
  add column if not exists target_key           text,
  add column if not exists cost_fraction        numeric(9,6),
  add column if not exists price_per_share      numeric(18,6),
  add column if not exists quantity             numeric(18,4);

-- Existing rows carry only a multiplier. Expressed as a ratio that is "one
-- share becomes m", which is exactly what the multiplier meant.
update corporate_actions
   set ratio_from = coalesce(ratio_from, case when quantity_multiplier is not null then 1 end),
       ratio_to   = coalesce(ratio_to, quantity_multiplier)
 where ratio_from is null or ratio_to is null;

update corporate_actions
   set target_key = coalesce(target_isin, '')
 where target_key is null;

alter table corporate_actions
  alter column target_key set default '',
  alter column target_key set not null;

alter table corporate_actions
  drop constraint if exists corporate_actions_unique;

alter table corporate_actions
  add constraint corporate_actions_unique
  unique (isin, action_type, ex_date, target_key);

-- Demergers and mergers are looked up by where they send the holding.
create index if not exists corp_actions_target_idx
  on corporate_actions(target_isin)
  where target_isin is not null;

commit;
